[sidebar.openSidebar]
description = "Open the sidebar with the last opened content"
match = """
  (open | show |) (my | the |) sidebar (for me|)
"""

[[sidebar.openSidebar.example]]
phrase = "open sidebar"
test = true
